#!/bin/sh
 # | cut -d '/' -f 1
 lines=$(nmcli device wifi list | grep '^[\*\ ]' |
     sed 's/^\(\**\)\ *[A-Z:0-9]*\ *\(.*[^\ ]\)\ *Infra\ *[0-9\ ]*Mbit\/s[0-9\ ]*\([^\ ]*\)\ *\(.*[^\ ]\)\ *$/\1|\2|\3|\4\\n/')
# security=
# read password
# nmcli device wifi connect $SSID password $password

connected=$(echo -e $lines | grep '^\ *\*')
name=$(echo $connected | cut -d '|' -f 2)
signal=$(echo $connected | cut -d '|' -f 3)
echo $signal $name
