#!/bin/sh

# Shows the price for desired cryptocurrencies. Module updates automatically
# every calendar day, but can also be updated with a middle click.

# coins to print
coins="btc eth"

refresh=''

# Directory where currency info is stored.
dir="${XDG_DATA_HOME:-$HOME/.local/share}/crypto-prices"

printprices() { # Print/format all prices
	for coin in $coins; do
        coinfile="$dir/$coin-price"
		[ -f "$coinfile" ] || continue
		icon="$(cut -d';' -f1 "$coinfile")"
		price="$(cut -d';' -f2 "$coinfile")"
		printf "%s%.2f€ " $icon $price
	done | sed 's/ $/\n/'
	}

# If currencies haven't been updated today, try to update them.
[ "$(stat -c %x "$dir" | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
	{ ping -q -c 1 example.org >/dev/null 2>&1 && crypto-update || exit ;}

case $BUTTON in
	1) cat "$dir"/*-chart > "$dir"/tmp
        setsid "$TERMINAL" -e less -SRf "$dir"/tmp
        rm "$dir"/tmp;;
    2) echo -n $refresh" "; printprices
        ping -q -c 1 example.org >/dev/null 2>&1 && crypto-update || notify-send "No Network!";;
	3) uptime="$(date -d "$(stat -c %x "$dir")" '+%D at %T' | sed "s|$(date '+%D')|Today|")"
        notify-send "Crypto-currency module" "\- Right check all crypto prices.
- Middle click to update.
- Right click to see 7 days charts.
- Shows "$refresh" if updating prices.
- Manually add/remove currencies to list in the script.
Exact prices in USD:
$(awk -F';' '{print $1, $3 ":\n\t$" $2}' "$dir"/*-price)
<b>Last updated:</b>$uptime" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

printprices
