#! /bin/sh

colors=$(xrdb -query)

COLOR_MONITOR_FG=$(echo "$colors" | awk '/foreground:/ {print $2}')
COLOR_MONITOR_BG=$(echo "$colors" | awk '/background:/ {print $2}')
COLOR_FOCUSED_MONITOR_FG=$(echo "$colors" | awk '/color15:/ {print $2}')
COLOR_FOCUSED_MONITOR_BG=$(echo "$colors" | awk '/fadeColor:/ {print $2}')
COLOR_FREE_FG=$(echo "$colors" | awk '/foreground:/ {print $2}')
COLOR_FREE_BG=$(echo "$colors" | awk '/background:/ {print $2}')
COLOR_FOCUSED_FREE_FG=$(echo "$colors" | awk '/background:/ {print $2}')
COLOR_FOCUSED_FREE_BG=$(echo "$colors" | awk '/color6:/ {print $2}')
COLOR_OCCUPIED_FG=$(echo "$colors" | awk '/foreground:/ {print $2}')
COLOR_OCCUPIED_BG=$(echo "$colors" | awk '/fadeColor:/ {print $2}')
COLOR_FOCUSED_OCCUPIED_FG=$(echo "$colors" | awk '/background:/ {print $2}')
COLOR_FOCUSED_OCCUPIED_BG=$(echo "$colors" | awk '/color6:/ {print $2}')
COLOR_URGENT_FG=$(echo "$colors" | awk '/color15:/ {print $2}')
COLOR_URGENT_BG=$(echo "$colors" | awk '/color1:/ {print $2}')
COLOR_FOCUSED_URGENT_FG=$(echo "$colors" | awk '/foreground:/ {print $2}')
COLOR_FOCUSED_URGENT_BG=$(echo "$colors" | awk '/color1:/ {print $2}')
COLOR_LAYOUT_FG=$(echo "$colors" | awk '/color2:/ {print $2}')
COLOR_LAYOUT_BG=$(echo "$colors" | awk '/background:/ {print $2}')

num_mon=$(bspc query -M | wc -l)
line=$(bspc subscribe -c 1 report)

case $line in
    W*)
        # bspwm's state
        wm=""
        IFS=':'
        set -- ${line#?}
        while [ $# -gt 0 ] ; do
            item=$1
            name=${item#?}
            case $item in
                [mM]*)
                    case $item in
                        m*)
                            # monitor
                            FG=$COLOR_MONITOR_FG
                            BG=$COLOR_MONITOR_BG
                            on_focused_monitor=
                            ;;
                        M*)
                            # focused monitor
                            FG=$COLOR_FOCUSED_MONITOR_FG
                            BG=$COLOR_FOCUSED_MONITOR_BG
                            on_focused_monitor=1
                            ;;
                    esac
                    [ $num_mon -lt 2 ] && shift && continue
                    wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
                    ;;
                [fFoOuU]*)
                    case $item in
                        f*)
                            # free desktop
                            shift && continue
                            ;;
                        F*)
                            if [ "$on_focused_monitor" ] ; then
                                # focused free desktop
                                FG=$COLOR_FOCUSED_FREE_FG
                                BG=$COLOR_FOCUSED_FREE_BG
                                UL=$BG
                            else
                                # active free desktop
                                FG=$COLOR_FREE_FG
                                BG=$COLOR_FREE_BG
                                UL=$COLOR_FOCUSED_FREE_BG
                            fi
                            ;;
                        o*)
                            # occupied desktop
                            FG=$COLOR_OCCUPIED_FG
                            BG=$COLOR_OCCUPIED_BG
                            UL=$BG
                            ;;
                        O*)
                            if [ "$on_focused_monitor" ] ; then
                                # focused occupied desktop
                                FG=$COLOR_FOCUSED_OCCUPIED_FG
                                BG=$COLOR_FOCUSED_OCCUPIED_BG
                                UL=$BG
                            else
                                # active occupied desktop
                                FG=$COLOR_OCCUPIED_FG
                                BG=$COLOR_OCCUPIED_BG
                                UL=$COLOR_FOCUSED_OCCUPIED_BG
                            fi
                            ;;
                        u*)
                            # urgent desktop
                            FG=$COLOR_URGENT_FG
                            BG=$COLOR_URGENT_BG
                            UL=$BG
                            ;;
                        U*)
                            if [ "$on_focused_monitor" ] ; then
                                # focused urgent desktop
                                FG=$COLOR_FOCUSED_URGENT_FG
                                BG=$COLOR_FOCUSED_URGENT_BG
                                UL=$BG
                            else
                                # active urgent desktop
                                FG=$COLOR_URGENT_FG
                                BG=$COLOR_URGENT_BG
                                UL=$COLOR_FOCUSED_URGENT_BG
                            fi
                            ;;
                    esac
                    wm="${wm}%{F${FG}}%{B${BG}}%{U${UL}}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}%{-u}"
                    ;;
                L*)
                    # layout
                    wm="${wm}%{F$COLOR_LAYOUT_FG}%{B$COLOR_LAYOUT_BG} ${name} %{B-}%{F-}"
                    ;;
            esac
            shift
        done
        ;;
esac
echo "$wm"
