#!/bin/sh

clock=$(date '+%I')

cmd1='%{A1:setsid -f "$TERMINAL" --class=floatterm -e calcurse:}'
cmd3='%{A3:aps=$(calcurse -d3); notify-send "$([ $aps ] || echo -n "No ")Appointments" "$aps":}'
closecmd='%{A}'

datetime=$(date "+%Y %b %d (%a) %I:%M%p")

echo "$cmd1$cmd3$datetime$closecmd$closecmd"
