#!/bin/sh

# Shows the price for desired cryptocurrencies. Module updates automatically
# every calendar day, but can also be updated with a middle click.

# coins to print
coins="btc eth"

# Directory where currency info is stored.
dir="${XDG_DATA_HOME:-$HOME/.local/share}/crypto-prices"

cmd1='%{A1:setsid -f "$TERMINAL" --class floatterm -e getcrypto:}'
cmd3='%{A3:pkill -RTMIN+13 statusblocks:}'
closecmd='%{A}'

printcrypto(){
    echo "$cmd1$cmd3$prices$closecmd$closecmd"
}

prices=$(getcrypto -1b "$coins")

printcrypto
