#!/bin/sh

# Show wifi and percent strength
# Show ethernet

wifiup='直'
ethup=''
wifidown='睊'
ethdown=''

case $BUTTON in
	1) "$TERMINAL" -e nmtui; pkill -RTMIN+4 dwmblocks ;;
	3) notify-send "Internet module" "\- Click to connect
$wifidown: looking for wifi connection
$wifiup:wifi connection with quality
$ethdow no ethernet
$ethupthernet working" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) wifistat=$wifidown ;;
	up) wifistat="$(awk '/^\s*w/ { print "wifiup" int($3 * 100 / 70) "%" }' /proc/net/wireless | sed "s/wifiup/$wifiup/")" ;;
esac

printf "%s%s\n" "$wifistat" "$(sed "s/down/$ethdown/;s/up/$ethup/" /sys/class/net/e*/operstate 2>/dev/null)"
