#!/bin/sh

# Show wifi and percent strength
# Show ethernet

wifiup='直'
ethup=''
wifidown='睊'
ethdown=''

cmd1='%{A1:setsid -f "$TERMINAL" --class floatterm -e connmanctl; pkill -RTMIN+4 statusblocks:}'
closecmd='%{A}'

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) wifi=$wifidown ;;
	up) wifi="$(awk '/^\s*w/ { print "wifiup" int($3 * 100 / 70) "%" }' /proc/net/wireless | sed "s/wifiup/$wifiup/")" ;;
esac
eth=$(sed "s/down/$ethdown/;s/up/$ethup/" /sys/class/net/e*/operstate 2>/dev/null)

echo "$cmd1$wifi$eth$closecmd"
