#!/bin/sh

# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

icon='參'
cmd1='%{A1:setsid -f "$TERMINAL" --class floatterm -e newsboat:}'
cmd3='%{A3:setsid -f news-update:}'
closecmd='%{A}'

news=$(newsboat -x print-unread | awk '{ if($1>0) print $1}')

printnews(){
    echo "$cmd1$cmd3$icon$news$closecmd$closecmd"
}


[ -e /tmp/newsupdate ] && {
    cat /tmp/newsupdate
    rm -f /tmp/newsupdate
} || printnews | tee /tmp/newsupdate
