#!/bin/sh

# Prints the current volume
muted="ﱝ"
high="墳"
medium="奔"
low="奄"

cmd1='%{A1:setsid -f "$TERMINAL" --class floatterm -e pulsemixer; until pidof pulsemixer; do pkill -RTMIN+10 statusblocks; sleep 1; done:}'
cmd3='%{A3:pamixer -t; pkill -RTMIN+10 statusblocks:}'
cmd4='%{A4:pamixer --allow-boost -i 1; pkill -RTMIN+10 statusblocks:}'
cmd5='%{A5:pamixer --allow-boost -d 1; pkill -RTMIN+10 statusblocks:}'
closecmd='%{A}'

if [ $(pamixer --get-mute) = true ]; then
    vol=$muted
else
    vol="$(pamixer --get-volume)"
    if [ "$vol" -gt "70" ]; then
        icon="$high"
    elif [ "$vol" -lt "30" ]; then
        icon="$low"
    else
        icon="$medium"
    fi
    vol="$vol"'%%'
fi

echo "$cmd1$cmd3$cmd4$cmd5$icon$vol$closecmd$closecmd$closecmd$closecmd"
