#!/bin/sh

# Prints the current volume
muted="ﱝ "
high=" "
medium= ""
low=" "

case $BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send "Volume module" "\- Shows volume, $muted if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pamixer --get-mute) = true ] && echo $muted && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon=$high
elif [ "$vol" -lt "30" ]; then
	icon=$low
else
	icon=$medium
fi

echo "$icon$vol%"
