#!/bin/sh

light_file="/sys/class/backlight/intel_backlight/brightness"
max_light=$(cat /sys/class/backlight/intel_backlight/max_brightness)
light=$(cat $light_file)

case "$1" in
    -i)
        light=$(($light + $2*$max_light/100));;
    -d)
        light=$(($light - $2*$max_light/100));;
    -s)
        light=$(($2*$max_light/100));;
    *)
        echo option $1 is not recognized.;;
esac

light=$(($light>$max_light ? $max_light:$light))

echo $light > $light_file
