#!/bin/sh

while [ -z $stop ]; do
    eq=$(dmenu -p "calculate >")
    [ -z "$eq" ] && exit 1
    ans=$(echo "$eq" | bc -l)
    echo $?
    choices="copy\nclear\nquit"
    choice=$(printf "$choices" | dmenu -p "= $ans")
    case $choice in
        copy)
            printf "$ans" | xclip -sel clip
            notify-send "bcmenu" "'$ans' copied to clipboard."
            stop=1
            ;;
        clear)
            ;;
        quit)
            stop=1
            ;;
        *)
            stop=1
            notify-send "bcmenu" "unrecognized option '$choice'."
            ;;
    esac
done
