#!/bin/sh

configure_desktops(){
    # configure_desktops dp1[ dp2[ dp3]]
    rules="|1:9|2:4 5|3:3 3 3|"
    desktops="123456789"
    rule=$(echo "$rules" |
        sed 's/^.*|'"$#"':\([0-9 ]\+\)|.*$/\1/')
    from_num=1
    for num in $rule; do
        to_num=$((from_num+num-1))
        args=$(echo "$desktops" |
            cut -c"$from_num-$to_num" |
            sed 's/\([0-9]\)/\1 /g')
        bspc monitor "$1" -d "$args"
        shift
        from_num=$((from_num+num))
    done
}

get_layout(){
    xrandr --listactivemonitors |
        sed -n 's/^\s*[0-9]\+:.*\s\+[0-9]\+\/[0-9]\+x[0-9]\+\/[0-9]\++\([0-9]\+\)+\([0-9]\+\)\s\+\([\w\-]\+\)$/\3 \1 \2/p' |
        awk '{print $1 " " $2+$3}' | sort -k2 | cut -d' ' -f 1
}

# configure desktops
configure_desktops "$(get_layout)"
