#!/bin/sh

rules="|1:9|2:4 5|3:3 3 3|"
desktops="123456789"

layout=$(xrandr --listactivemonitors |
        sed -n 's/^\s*[0-9]\+:.*\s\+[0-9]\+\/[0-9]\+x[0-9]\+\/[0-9]\++\([0-9]\+\)+\([0-9]\+\)\s\+\(.\+\)$/\3 \1 \2/p' |
        awk '{print $1 " " $2+$3}' | sort -k2 | cut -d' ' -f 1)
rule=$(echo "$rules" |
    sed 's/^.*|'"$(echo "$layout" | wc -l)"':\([0-9 ]\+\)|.*$/\1/')

from_num=1
for num in $rule; do
    to_num=$((from_num+num-1))
    args=$(echo "$desktops" |
        cut -c"$from_num-$to_num" |
        sed 's/\([0-9]\)/\1 /g;s/ $/ /')
    monitor=$(echo "$layout" | head -n 1)
    layout=$(echo "$layout" | grep -v "$monitor")
    bspc monitor "$monitor" -d $args

    from_num=$((from_num+num))
done

active_monitors=$(xrandr --listactivemonitors | awk '/^\s*[0-9]+:/ {print $4}')
inactive_monintors=(for m in $monitors; do echo "$active_monitors" | grep -q "$m" || echo "$m"; done)
for m in $inactive_monintors; do
    bspc monitor "$m" --remove
done
