#!/bin/sh

_bluetoothctl() {
    LC_ALL=C timeout 30 bluetoothctl
}

notify() {
    msg=${1?BUG: no message}
    urgency=${2-normal}

    if command -v notify-send >/dev/null 2>&1; then
        notify-send -u "$urgency" "  dm-bluetooth" "$msg"
    fi
}

get_devices() {
    echo "devices" | _bluetoothctl | grep 'Device' | cut -d' ' -f2-
}

get_new_devices() {
    wait_time="5"
    notify "ﴽ  scanning ...\nplease wait ${wait_time}s"
    echo -e "$(timeout "$wait_time" bluetoothctl -- scan on)" | grep 'NEW' | cut -d' ' -f3-
    printf 'scan off\n' | _bluetoothctl 2>&1 >/dev/null
}

power_off() {
    echo "power off" | _bluetoothctl
    notify "Turned off bluetooth"
}

power_on() {
    if bluetooth | grep 'off'; then
        sudo -A rfkill unblock bluetooth
    fi
    echo "power on" | _bluetoothctl
    notify "Turned on bluetooth"
}

connect_disconnect() {
    mode=${1?BUG: missing mode}
    retries=15

    # useful variables to avoid code duplicates
    case $mode in
        "connect")
            preposition=to
            expected_to_connect=yes
        ;;
        "disconnect")
            preposition=from
            expected_to_connect=no
        ;;
    esac

    # get device or scan
    devices=$(get_devices)
    scan="scan for new device"
    options=$(printf "$devices" | cut -d' ' -f2-; echo "$scan")
    name=$(printf "$options" | dmenu -ip "choose device: " -l 10)
    [ -z $name ] && exit 0 || printf 'power on\n' | _bluetoothctl

    # scan new device
    if [ "$name" = "$scan" ] && [ "$mode" = "connect" ]; then
        while [ -z "$gotit" ]; do
            devices=$(get_new_devices)
            options=$(echo "retry"; printf "$devices" | cut -d' ' -f2-)
            name=$(printf "$options" | dmenu -ip "choose device: " -l 10)
            if [ -z "$name" ]; then
                power_off
                exit 1
            elif [ "$name" != "retry" ]; then
                gotit=1
            fi
        done
        mac=$(echo $devices | grep "$name" | cut -d' ' -f1)
        printf 'trust %s\npair %s\n' "$mac" "$mac" | _bluetoothctl
    else
        mac=$(printf "$devices" | grep "$name" | cut -d' ' -f1)
    fi

    # try to cennect/disconnect iteratively
    notify "Attempting to $mode $preposition $name"
    i=1
    while [ "$i" -ne "$retries" ]; do
        printf '%s %s\n' "$mode" "$mac" | _bluetoothctl
        if printf 'info %s\n' "$mac" |
            _bluetoothctl |
            grep -Pq '^[\t ]+Connected: '"$expected_to_connect"; then
            notify "${mode}ed $preposition $name"
            [ "$mode" = "disconnect" ] && power_off
            exit 0
        fi
        sleep 1
        i=$((i + 1))
    done

    # case of failure
    ret="$?"
    power_off
    notify "Failed to $mode $preposition $name. Try "'`sudo rfkill unblock bluetooth`.' "critical"
    return "$ret"
}

execute_mode(){
    local mode
    mode=${1?BUG: missing mode}

    case $mode in
        "connect"|"disconnect")
            power_on
            connect_disconnect $mode
        ;;
        "power off")
            power_off
        ;;
        *)
            [ $mode ] && notify "Unknown mode $mode"
            exit 1
        ;;
    esac

}

modes="connect
disconnect
power off"

choice=$(printf "$modes" | dmenu -il 10 -p "choose action: ")

execute_mode "$choice"
