#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md, .org.  Opens .sent files as sent
# presentations. Runs scripts based on extention or shebang.
#
# Note that .tex files which you wish to compile with XeLaTeX should have the
# string "xelatex" somewhere in a comment/command in the first 5 lines.

if [ "$1" = "--onlythis" ]; then
	onlythis=1
	shift
else
	onlythis=
fi

file=$(readlink -f "$1")

base="${file%.*}"
ext="${file##*.}"
name="${file##*/}"
namebase="${name%.*}"
dir="${file%/*}"

textype() {
	if [ -z "$onlythis" ]; then
		mainfile=$(head -n 5 "$file" | sed -n 's/\\documentclass\[\(.*\)\]{subfiles}/\1/p')
		[ -f "$mainfile" ] && file=$mainfile
	fi
	latexmk -pdf "$file" && latexmk -c "$file"
	[ -f "$namebase.pdf" ] && [ "$(readlink -f "$PWD")" !=  "$dir" ] && mv "$namebase".* "$dir"/
}

case "$ext" in
	# Try to keep these cases in alphabetical order.
	[0-9]) preconv "$file" | refer -PS -e | groff -mandoc -T pdf > "$base".pdf ;;
	c) gcc "$file" -o "$base" ;;
	cpp) g++ "$file" -o "$base" ;;
	cs) mcs "$file" && mono "$base".exe ;;
	h) make ;;
	md)	pandoc -o "$base".pdf "$file";;
	mom) preconv "$file" | refer -PS -e | groff -mom -kept -T pdf > "$base".pdf ;;
	ms) preconv "$file" | refer -PS -e | groff -me -ms -kept -T pdf > "$base".pdf ;;
	rs) cargo build ;;
	sass) sassc -a "$file" "$base.css" ;;
	tex) textype ;;
	*) printf "No compiling method for '.%s' files" "$ext" ;;
esac
