#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md, .org.  Opens .sent files as sent
# presentations. Runs scripts based on extention or shebang.
#
# Note that .tex files which you wish to compile with XeLaTeX should have the
# string "xelatex" somewhere in a comment/command in the first 5 lines.

file=$(readlink -f "$1")
dir=${file%/*}
start_dir="$PWD"

cd "$dir" || exit 1

file="${file##*/}"
base="${file%.*}"
ext="${file##*.}"

textype() {
	cd "$start_dir" || exit 1
	if [ -f main.tex ]; then
		file="main.tex"
		base="main"
	else
		printf "main.tex not found. Running on %s\n" "$file"
		cd "$dir" || exit 1
	fi
	command="pdflatex"
	( head -n5 "$file" | grep -qi 'xelatex' ) && command="xelatex"
	$command "$base" &&
	grep -v '^\%' "$file" | grep -qi '\\bib' &&
	bibtex "$base" &&
	$command "$base" &&
	$command "$base"
}

case "$ext" in
	# Try to keep these cases in alphabetical order.
	[0-9]) preconv "$file" | refer -PS -e | groff -mandoc -T pdf > "$base".pdf ;;
	c) cc "$file" -o "$base" && "$base" ;;
	cpp) g++ "$file" -o "$base" && "$base" ;;
	cs) mcs "$file" && mono "$base".exe ;;
	h) sudo make install ;;
	md)	pandoc -o "$base".pdf "$file";;
	mom) preconv "$file" | refer -PS -e | groff -mom -kept -T pdf > "$base".pdf ;;
	ms) preconv "$file" | refer -PS -e | groff -me -ms -kept -T pdf > "$base".pdf ;;
	rs) cargo build ;;
	sass) sassc -a "$file" "$base.css" ;;
	tex) textype ;;
	*) head -n1 "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ;;
esac
