#!/bin/sh

options="lock
suspend
poweroff
reboot"

choice=$(echo "$options" | dmenu -p "select: ")

case "$choice" in
    "lock") lock;;
    "suspend") loginctl suspend;;
    "poweroff") loginctl poweroff;;
    "reboot") loginctl reboot;;
    *) exit
esac
