#!/bin/sh

[ -z "$1" ] && exit 1
dotfiles_dir="$HOME/dotfiles"
full=$(realpath "$1")
relative="${full#"$PWD/"}"
mkdir -p "$(dirname "$dotfiles_dir/$relative")"
mv "$full" "$dotfiles_dir/$relative"
ln -s "$dotfiles_dir/$relative" "$full"
