#!/bin/sh

usage(){
    echo "Usage: dotctl add|remove file1 file2 ..."
}

add(){
	mkdir -p "$(dirname "$dst")"
	$sudocmd cp "$src" "$dst"
	$sudocmd ln -sf "$dst" "$src"
}

remove(){
	[ -n "$i" ] && {
		if [ -e "$dst" ]; then
			$sudocmd trash-put "$src"
			$sudocmd mv "$dst" "$src"
		else
			echo "Skipping $i as is not synched!"
		fi
	}
}

case "$1" in
    add|remove)
		command=$1
        shift
		for i in "$@"; do
			dotfiles_dir="${DOTFILES_DIR:-"$HOME/.dotfiles"}"
			src=$(realpath -s "$i")
			if echo "$src" | grep -q "$HOME"; then
				dst="$dotfiles_dir/home/${src#"$HOME/"}"
				sudocmd=
			else
				dst="$dotfiles_dir/root/$src"
				sudocmd=sudo
			fi
			echo "$i"
			$command "$i"
		done
        ;;
	-h|--help|help)
		usage
		exit
		;;
    *)
        [ -z "$1" ] && echo "Please specify command."
        usage
		exit 1
        ;;
esac
