#!/bin/sh

dotfiles_dir="${DOTFILES_DIR:-"$HOME/.dotfiles"}"

usage(){
    echo "Usage: dotctl add|remove file1 file2 ..."
}

add(){
    for i in $@; do
        src=$(realpath "$i")
        dst="$dotfiles_dir/${src#$HOME/}"
        mkdir -p "$(dirname "$dst")"
        mv "$src" "$dst"
        ln -s "$dst" "$src"
    done
}

remove(){
    for i in $@; do
        [ -n "$i" ] && {
            src=$(realpath -s "$i")
            dst="$dotfiles_dir/${src#$HOME/}"
            if [ -e "$dst" ]; then
                trash-put "$src"
                mv "$dst" "$src"
            else
                echo "Skipping $i as is not synched!"
            fi
        }
    done
}

case "$1" in
    add)
        shift
        add $@
        ;;
    remove)
        shift
        remove $@
        ;;
    *)
        [ -z "$1" ] && echo "Please specify command."
        usage
        ;;
esac
