#!/bin/sh

generate(){
    mode=$(printf "dark\nlight" | dmenu -p "dark or light?")
    flavours generate "$mode" "$(cat "${XDG_DATA_HOME:-$HOME/.local/share}/wallpaper")"
    theme="generated"
}

if [ "$1" = "--generate" ]; then
    generate
else
    from_wallpaper="generate from wallpaper"
    choices=$(echo "$from_wallpaper"
        flavours list -l | grep -v 'generated'
    )

    theme=$(echo "$choices" | dmenu -p "choose theme:")
    if [ "$theme" = "$from_wallpaper" ]; then
        generate
    fi
fi


[ "$theme" ] && flavours apply "$theme" && bspc wm -r
