#!/bin/sh
# use fzf as it was dmenu or rofi.
# multi selection is enabled by default.
# TODO:
# - bottom deleting --reverse
# - lines using terminal geometry options
# - support for font and color options (if achievable)

x=0
y=20
w="100%"
maxlines=32
fontsize=11
args='--reverse --no-info --bind "tab:clear-query+execute-silent(xdotool type --delay 0 {})" --print-query'
usage='Usage: fzf script which replicates dmenu behaviour addfzf features.
use short dmenu options in the usual way.
fzf options can be using -L "--long-opt-1 --long-opt-2"'

usage() {
    echo "$usage"
}

if [ "$1" = "--parent-proc-id" ]; then
    parent_proc_id="$2"
    args=$(echo "$*" | sed 's/--parent-proc-id [0-9]* \(.*\)/\1/')
    if [ "$3" = "--lines" ]; then
        lines="$4"
        args=$(echo "$args" | sed 's/--lines [0-9]* \(.*\)/\1/')
    else
        lines=$(cat /tmp/fzfmenu-input | wc -l)
        [ $lines -gt $maxlines ] && lines=$maxlines
    fi

    wid=$(xdotool getactivewindow)
    xdotool windowmove "$wid" $x $y
    h=$((($lines+1) * $fontsize * 17/10))
    xdotool windowsize "$wid" $w $h

    out=$(ueberzug-wrap fzf "$args" </tmp/fzfmenu-input)
    choices_num=$(echo "$out" | wc -l)
    if [ "$choices_num" -le 1 ]; then
        echo "$out" >/proc/"$parent_proc_id"/fd/1
    else
        echo "$out" | sed -n '2,$p' >/proc/"$parent_proc_id"/fd/1
    fi
else
    while getopts "bfivl:m:p:L:h" option
    do
        case "${option}" in
            [bfm]) ;;
            i) args="-i $args";;
            v) fzf -v; exit 0;;
            p) args="$args --prompt='$OPTARG'";;
            l) args="--lines $OPTARG $args";;
            L) args="$args $OPTARG";;
            h) usage; exit 0;;
            *) echo "unsupported option $option. If it is a fzf option please use the long format."
                usage; exit 1;;
        esac
    done
    shift $((OPTIND-1))

    cat /proc/"$$"/fd/0 > /tmp/fzfmenu-input
    $TERMINAL --class 'floatterm' -t 'fzfmenu' -e fzfmenu --parent-proc-id "$$" $args
fi
