#!/bin/sh
# use fzf as it was dmenu or rofi.
# multi selection is enabled by default.
# TODO:
# - monitor support with xdotool or wmctrl
# - bottom deleting --reverse
# - lines using terminal geometry options
# - support for font and color options (if achievable)

args="--reverse --no-info --multi --print-query"

usage() {
echo "Usage: fzfmenu [-h] [-p prompt]"
}

while getopts "bfivl:m:p:h" option
do
	case "${option}" in
        b) ;;
        f) ;;
		i) args="$args -i";;
        v) fzf -v; exit 0;;
        l) ;;
        m) ;;
		p) args="$args --prompt=\'$OPTARG\'";;
		h) usage; exit 0;;
		*) echo "unsupported option $option. If it is a fzf option please use the long format."
            usage; exit 1;;
	esac
done
shift $((OPTIND-1))
args="$args $*"

$TERMINAL -t fzfmenu -e sh -c 'out=$(ueberzug-wrap fzf '"$args"' </proc/'"$$"'/fd/0)
lines=$(echo "$out" | wc -l)
if [ "$lines" -le 1 ]; then
    echo "$out" >/proc/'"$$"'/fd/1
else
    echo "$out" | sed -n '"'"'2,$p'"'"' >/proc/'"$$"'/fd/1
fi'
