#!/bin/bash

num=1

usage() {
echo "Usage: get-rand-img [-n number_of_images] dir"
}

while getopts "n:h" option
do
	case "${option}" in
		n)
            num=${OPTARG};;
		h)
            usage
            exit 0;;
		*)
            echo "Error!" 1>&2
            usage >&2
            exit 1;;
	esac
done
shift $((OPTIND-1))

find "$1" -type f | shuf -n $num
