#!/bin/bash
# usage example:
# getrandimgs number_of_images from_dir to_dir
num=10
ext="jpg"

usage() {
echo "Usage: ./getrandimgs [ -n number_of_images ] [ -e extension ] from_dir to_dir"
}
while getopts "n:e:h" option
do 
	case "${option}" in 
		n) 
		num=${OPTARG};; 
		e) 
		ext=${OPTARG};; 
		h)
		usage
		exit 1;;
		*)
		echo "Error!" 1>&2
		usage >&2
		exit 1;;
	esac 
done 
shift $((OPTIND-1))

if [ $num -eq -1 ]
then
	find "$1" -iname "*.$ext" | sed 's/\ /\\ /g' > tmp
else
	find "$1" -iname "*.$ext" | shuf -n $num | sed 's/\ /\\ /g' > tmp
fi

k=1
while read img
do
	cp "$img" $2$k"."$ext
	if [ "$ext"=="TIF" ]
	then
		convert -quiet $2$k".TIF" $2$k".png"
	fi
	((k=$k+1))
done < tmp
rm tmp
