#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Get user selection via dmenu from emoji file.
iconsfile="$HOME/.local/share/unicode-list"
chosen=$(cat "$iconsfile" | dmenu -i -l 30 -p "select icon:" | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

printf "$chosen" | xclip -selection clipboard
notify-send "$chosen copied to clipboard."
