#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Get user selection via dmenu from emoji file.
iconsfile="$HOME/.local/share/unicode-list"
chosen=$(rofi -dmenu -multi-select -i -l 30 -p "select icon:" < "$iconsfile"| sed "s/ .*//" | tr -d '\n')

# Exit if none chosen.
[ -z "$chosen" ] && exit

printf "%s" "$chosen" | xclip -selection clipboard
notify-send "$chosen copied to clipboard."
