#!/bin/sh

colors=$(xrdb -query)

white=$(echo "$colors" | awk '/foreground:/ {print $2}')
blue=$(echo "$colors" | awk '/color4:/ {print $2}')
black=$(echo "$colors" | awk '/background:/ {print $2}')
red=$(echo "$colors" | awk '/color1:/ {print $2}')
green=$(echo "$colors" | awk '/color2:/ {print $2}')
lightblue=$(echo "$colors" | awk '/color6:/ {print $2}')

tmpimg=/tmp/lockimg
image=$(cat "${XDG_DATA_HOME:-~/.local/share}"/wallpaper)
screendims=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
convert "$image" -resize "$screendims"^ "$tmpimg"

i3lock \
--insidever-color=$white \
--ringver-color=$lightblue \
\
--insidewrong-color=$white \
--ringwrong-color=$red \
\
--inside-color=$white \
--ring-color=$blue \
--line-color=$black \
--separator-color=$black \
\
--verif-color=$black \
--wrong-color=$black \
--time-color=$black \
--date-color=$black \
--keyhl-color=$green \
--bshl-color=$red \
\
--screen 1 \
--blur 5 \
--clock \
--indicator \
--time-str="%H:%M:%S" \
--date-str="%Y %b %d (%a)" \
--pass-media \
--image="$tmpimg"
