#!/bin/sh

tmpimg=/tmp/lockimg
image=$(cat "${XDG_DATA_HOME:-~/.local/share}"/wallpaper)
screendims=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')
echo "$screendims"

convert "$image" -resize "$screendims"^ "$tmpimg"
i3lock --image "$tmpimg"
