#!/bin/sh

colors=$(xrdb -query)

white=$(echo "$colors" | awk '/foreground:/ {print $2}')
blue=$(echo "$colors" | awk '/color4:/ {print $2}')
black=$(echo "$colors" | awk '/background:/ {print $2}')
red=$(echo "$colors" | awk '/color1:/ {print $2}')
green=$(echo "$colors" | awk '/color2:/ {print $2}')
lightblue=$(echo "$colors" | awk '/color6:/ {print $2}')

cache_file="${XDG_CACHE_HOME:-"$HOME/.cache"}"/lock-info
cache_img="${XDG_CACHE_HOME:-"$HOME/.cache"}"/lock-img.jpg
curr_img=$(cat "${XDG_DATA_HOME:-"$HOME/.local/share"}"/wallpaper)
curr_geometries=$(xrandr --listactivemonitors |
        sed -n 's/^\s*[0-9]\+:.*\s\+\([0-9]\+\)\/[0-9]\+x\([0-9]\+\)\/[0-9]\++\([0-9]\+\)+\([0-9]\+\)\s.*$/\1 \2 \3 \4/p')

if [ "$1" = '--debug' ]; then
    rm "$cache_file"
    debug=1
fi

create_cache_img(){
    screendims=$(xdpyinfo |
        sed -n 's/^\s*dimensions:\s*\([0-9]\+x[0-9]\+\).*$/\1/p')
    convert -size "$screendims" xc:skyblue "$cache_img"
    echo "$curr_geometries" | while read width height xoff yoff
    do
        convert "$cache_img" \
            \( "$curr_img" -resize "${width}x${height}^" -gravity center -extent "${width}x${height}^" \) \
            -gravity northwest \
            -geometry "+${xoff}+${yoff}" -composite "$cache_img"
        [ $debug ] && sxiv "$cache_img"
    done
}

if [ -f "$cache_file" ]; then
    IFS=',' read old_img old_geometries < "$cache_file"
    old_geometries=$(echo "$old_geometries" | tr '|' '\n')
    if [ "$old_img" != "$curr_img" \
        -o "$old_geometries" != "$curr_geometries" ]
    then
        create_cache_img
        echo "$curr_img,$(echo "$curr_geometries" | tr '\n' '|')" > "$cache_file"
    else
        echo "using cached version"
    fi
else
    create_cache_img
    echo "$curr_img,$(echo "$curr_geometries" | tr '\n' '|')" > "$cache_file"
fi

if [ ! $debug ]; then
    i3lock \
    --insidever-color=$white \
    --ringver-color=$lightblue \
    \
    --insidewrong-color=$white \
    --ringwrong-color=$red \
    \
    --inside-color=$white \
    --ring-color=$blue \
    --line-color=$black \
    --separator-color=$black \
    \
    --verif-color=$black \
    --wrong-color=$black \
    --time-color=$black \
    --date-color=$black \
    --keyhl-color=$green \
    --bshl-color=$red \
    \
    --screen 1 \
    --blur 5 \
    --clock \
    --indicator \
    --time-str="%H:%M:%S" \
    --date-str="%Y %b %d (%a)" \
    --pass-media \
    --image="$cache_img"
fi
