#!/bin/sh

layouts="laptop-only
fullHD-VGA-above
fullHD-VGA-left"

[ "$1" ] && layout="$1" || layout=$(echo "$layouts" | dmenu -p 'choose layout: ')

# feed fifo file to inform statusbar of wm changes
PANEL_FIFO=/tmp/panel-fifo
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
bspc subscribe report > "$PANEL_FIFO" &

case $layout in
    laptop-only)
        xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal \
            --output VGA-1 --off \
            --output HDMI-1 --off
        bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
        bspc monitor VGA-1 --remove
        bspc monitor HDMI-1 --remove
        ;;
    fullHD-VGA-above)
        xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal \
            --output VGA-1 --mode 1920x1080 --above eDP-1 --rotate normal \
            --output HDMI-1 --off
        bspc monitor VGA-1 -d 1 2 3
        bspc monitor eDP-1 -d 4 5 6 7 8 9
        bspc monitor HDMI-1 --remove
        ;;
    fullHD-VGA-left)
        xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal \
            --output VGA-1 --mode 1920x1080 --left-of eDP-1 --rotate normal \
            --output HDMI-1 --off
        bspc monitor VGA-1 -d 1 2 3
        bspc monitor eDP-1 -d 4 5 6 7 8 9
        bspc monitor HDMI-1 --remove
        ;;
    *)
        echo "unknown layout $layout."
        exit 1
        ;;
esac

xsetwacom set "$(xsetwacom --list | awk '/stylus/ {print $8}')" maptooutput eDP-1
xsetwacom set "$(xsetwacom --list | awk '/eraser/ {print $8}')" maptooutput eDP-1
setwall --refresh &
pkill -x launchbar > /dev/null
launchbar bar1 &
