#!/bin/sh

for file in "$*"; do
    case "$file" in
        *.pdf)
            zathura "$file"
            ;;
        *.ps|*.eps|*.ps.gz|*.djvu)
            zathura "$*"
            exit
            ;;
        *.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.mov)
            mpv "$file" &
            ;;
        *.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx|*.as[fx])
            mpv "$file" &
            ;;
        *.bmp|*.jpg|*.jpeg|*.png|*.gif|*.xpm)
            sxiv "$*" &
            exit
            ;;
        *.odt|*.doc|*.docx|*.xls|*.xlsx|*.odp|*.pptx)
            libreoffice "$file" &
            ;;
        *.xopp)
            xournalpp "$file" 2>/dev/null &
            ;;
        *.o )
            nm "$file" | less
            ;;
        *.[1-8])
            man ./"$file"
            ;;
        *.asc)
            !!gpg --verify "$file"
            ;;
        *.zip|*.jar|*.war|*.ear|*.oxt|*.apkg)
            zip -sf "$file" | less
            ;;
        *)
            $EDITOR $*
            exit
            ;;
    esac
done
