#!/bin/sh

# define variables
passdir=${PASSWORD_STORE_DIR-~/.password-store}
pattern="$(printf "$passdir"/ | sed -e 's/\//\\\//g' -e 's/\./\\\./g')"'\(.*\).gpg'
passwords=$(find "$passdir" -name *.gpg | tr ' ' '\n' | sed 's/'"$pattern"'/\1/g')
commands='new password
edit password'
entries=$(echo "$commands"; echo "$passwords")

# define functions
get_password(){
    if [ "$typeit" -eq 0 ]; then
        pass show -c "$1" 2>/dev/null
    else
        pass show "$1" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
    fi
}
create_password(){
    exit
}
edit_password(){
    exit
}

# get args
typeit=0
if [ "$1" = "--type" ]; then
	typeit=1
	shift
fi


# get dmenu and xdotool commands
if [ -n "$DISPLAY" ]; then
	dmenu="dmenu"
	xdotool="xdotool type --clearmodifiers --file -"
elif [ -n "$WAYLAND_DISPLAY" ]; then
    echo "way $WAYLAND_DISPLAY"
	dmenu=dmenu-wl
	xdotool="ydotool type --file -"
else
    dmenu="fzf"
    xdotool="tee"
fi

choice=$(echo "$entries" | "$dmenu" "$@")

[ -n "$choice" ] || exit
case "$choice" in
    "new password") create_password;;
    "edit password") edit_password;;
    *) get_password "$choice";;
esac
