#!/bin/sh

# Show wifi and percent strength
# Show ethernet

wifiup='直'
ethup=''
wifidown='睊'
ethdown=''

cmd1='%{A1:setsid -f "$TERMINAL" --class=floatterm -e connmanctl:}'
en_dis_able=$(connmanctl technologies | sed -n '/ = wifi/{n;p}' | sed 's/^.*True$/disable/;s/^.*False$/enable/')
cmd3='%{A3:connmanctl '"$en_dis_able"' wifi && notify-send "'"$en_dis_able"'ed wifi":}'
closecmd='%{A}'

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) wifi=$wifidown ;;
	up) wifi="$(awk '/^\s*w/ { print "'"$wifiup"'" int($3 * 100 / 70) "%" }' /proc/net/wireless)" ;;
esac
eth=$(sed "s/down/$ethdown/;s/up/$ethup/" /sys/class/net/e*/operstate 2>/dev/null)

echo "$cmd1$cmd3$wifi$eth$closecmd$closecmd"
