#!/bin/sh

# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

icon='參'
cmd1='%{A1:setsid -f "$TERMINAL" --class floatterm -e newsboat:}'
cmd3='%{A3:pkill -RTMIN+6 statusblocks:}'
closecmd='%{A}'
endtime=20

cachefile="${XDG_CACHE_HOME:-~/.cache}"/sb-news-cache
printnews(){
    echo "$cmd1$cmd3$error$icon$news$closecmd$closecmd"
}

if [ "$(pgrep newsboat)" ]; then
    cat "$cachefile"
else
    msg=$(timeout "$endtime" newsboat -x reload)
    err=$?
    if [ "$msg" ]; then
        cat "$cachefile"
        exit
    elif [ "$err" -gt 0 ]; then
        error=""
    fi
    news=$(newsboat -x print-unread 2>/dev/null | awk '{print $1}')
    printnews | tee "$cachefile"
fi
