#!/bin/sh

wallfile="$HOME/.local/share/wallpaper"

# just refresh wallpaper
if [ "$1" = "--refresh" ]; then
    cat "$wallfile" | xargs xwallpaper --zoom
    exit
fi

# get argument
if [ -f "$1" ]; then
    img="$1"
else
    if [ -d "$1" ]; then
        dir="$1"
    else
        dir="$HOME"/media/wallpapers
    fi
    img=$(find -L "$dir" -type f | shuf -n 1)
fi

echo "$(realpath "$img")" >"$wallfile" && setwall --refresh
