#!/bin/sh

size=$(stty size)
h=${size% *}
w=${size#* }

x=0
y=0

echo "Press Enter to close"

view(){
    {
        printf '{ "action": "add", "identifier": "%s", "path": "%s",' "$ID_UEBERZUG" "$5"
        printf '"x": %d, "y": %d, "scaler": "fit_contain",' "$1" "$2"
        printf '"width": %d, "height": %d }\n' "$3" "$4"
    } > "$FIFO_UEBERZUG"
    read a
    printf '{ "action": "remove", "identifier": "%s" }\n' "$ID_UEBERZUG" > "$FIFO_UEBERZUG"
}

[ "$1" = "view" ] && view "$x" "$y" "$w" "$h" "$2" || ueberzug-wrap "$0" view "$1"

