#!/bin/sh

options="lock
suspend
hibernate
poweroff
reboot
logout"

choice=$(echo "$options" | dmenu -p "select:")

case "$choice" in
    "lock") lock;;
    "suspend") loginctl suspend;;
    "hibernate") loginctl hibernate;;
    "poweroff") loginctl poweroff;;
    "reboot") loginctl reboot;;
    "logout") loginctl terminate-session self;;
    *) exit
esac
