#!/bin/sh

options="lock
suspend
hibernate
poweroff
reboot
logout"

choice=$(echo "$options" | dmenu -p "select:")

case "$choice" in
    "lock") lock;;
    "suspend") systemctl suspend;;
    "hibernate") systemctl hibernate;;
    "poweroff") systemctl poweroff;;
    "reboot") systemctl reboot;;
    "logout") loginctl terminate-session self;;
    *) exit
esac
