#!/bin/sh

options="  lock
鈴  suspend
襤  poweroff
勒  reboot
  logout"

choice=$(echo "$options" | dmenu -p "select:" | awk '{print $2}')

case "$choice" in
    "lock") lock -s;;
    "suspend") systemctl suspend;;
    "poweroff") systemctl poweroff;;
    "reboot") systemctl reboot;;
    "logout") loginctl terminate-session self;;
    *) exit
esac
