#!/bin/sh

CACHE="$HOME/.cache/vifm/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$PWD/$6")" | sha256sum | awk '{print $1}'))"

pclear() {
    [ -p "$FIFO_UEBERZUG" ] &&
        printf '{ "action": "remove", "identifier": "%s" }\n' "$ID_UEBERZUG" > "$FIFO_UEBERZUG"
}

image() {
    [ -p "$FIFO_UEBERZUG" ] &&
    {
        printf '{ "action": "add", "identifier": "%s", "path": "%s", ' "$ID_UEBERZUG" "$6"
        printf '"x": %s, "y": %s, "scaler": "fit_contain",' "$2" "$3"
        printf '"width": %d, "height": %d }\n' "$4" "$5"
    } > "$FIFO_UEBERZUG" || identify "$6"
}

main() {
    case "$1" in
        "clear")
			pclear "$@"
			;;
        "draw")
			FILE="$PWD/$6"
			image "$1" "$2" "$3" "$4" "$5" "$FILE"
			;;
        "video")
			[ ! -f "$CACHE" ] && \
				ffmpegthumbnailer -i "$6" -o "${CACHE}.jpg" -s 0 -q 5
			image "$1" "$2" "$3" "$4" "$5" "${CACHE}.jpg"
			;;
        "epub")
			[ ! -f "$CACHE" ] && \
				epub-thumbnailer "$6" "$CACHE" 1024
			image "$1" "$2" "$3" "$4" "$5" "$CACHE"
			;;
        "pdf")
			[ ! -f "${CACHE}.jpg" ] && \
				pdftoppm -jpeg -f 1 -singlefile "$6" "$CACHE"
			image "$1" "$2" "$3" "$4" "$5" "${CACHE}.jpg"
			;;
        "audio")
			[ ! -f "${CACHE}.jpg" ] && \
				ffmpeg -i "$6" "${CACHE}.jpg" -y &> /dev/null
			image "$1" "$2" "$3" "$4" "$5" "${CACHE}.jpg"
			;;
        "font")
			[ ! -f "${CACHE}.jpg" ] && \
				fontpreview -i "$6" -o "${CACHE}.jpg"
			image "$1" "$2" "$3" "$4" "$5" "${CACHE}.jpg"
			;;
        *)
			echo "Unknown command: '$@'"
			;;
    esac
}
main "$@"
