#!/bin/sh

layout_dir="$HOME/.screenlayout"
current_layout_script="${XDG_DATA_HOME:-"$HOME/.local/share"}/current-layout"
tablet_monitor_file="${XDG_DATA_HOME:-"$HOME/.local/share"}/tablet-monitor"

if [ -f "$tablet_monitor_file" ]; then
    tablet_monitor=$(cat "$tablet_monitor_file")
else
    tablet_monitor="$(get_monitors | grep -i 'edp')"
fi

# get monitors
get_monitors(){
    xrandr -q | awk '/\s+connected.*/ {print $1}'
}

map_tablet(){
    if [ "$1" ]; then
        tablet_monitor="$1"
    else
        active_monitors=$(xrandr --listactivemonitors | awk '/^\s*[0-9]+:/ {print $4}')
        tablet_monitor=$(echo "$active_monitors" | dmenu -p 'choose monitor: ')
    fi
    xsetwacom set "$(xsetwacom --list | awk '/stylus/ {print $8}')" maptooutput "$tablet_monitor"
    xsetwacom set "$(xsetwacom --list | awk '/eraser/ {print $8}')" maptooutput "$tablet_monitor"
}

run(){
    if sh "$1"; then
        exit 0
    else
        notify-send -u critical "xrandrmenu" "Something went wrong!\nConnected monitors:\n$(get_monitors)"
        exit 1
    fi
}

restore(){
    run "$current_layout_script"
    map_tablet "$tablet_monitor"
}

apply(){
    if run "$1"; then
        ln -s "$1" "$current_layout_script"
        echo "$tablet_monitor" | tee "$tablet_monitor_file"
    fi
}

notify(){
    notify-send -u normal "xrandrmenu" "$@"
}

notify_err(){
    notify-send -u critical "xrandrmenu" "$@"
}

menu_loop(){
    while [ -z "$quit" ]; do
        layouts=$(find "$layout_dir" -executable -type f -exec basename {} \; | sed 's/\.sh//')
        choices="$layouts\ncreate new layout\nrestore\nmap tablet\nquit"
        choice=$(echo "$choices" | dmenu -p 'choose action: ')
        case "$choice" in
            'create new layout')
                notify "Save new layout in '~/.screenlayout' and exit Arandr"
                arandr
                ;;
            'map tablet')
                map_tablet
                ;;
            'restore')
                restore
                ;;
            'quit'|'')
                exit
                ;;
            *)
                layout_script="$layout_dir/$choice.sh"
                if [ -x "$layout_script" ]; then
                    apply "$layout_script"
                else
                    notify_err "Invalid option $choice"
                    exit 1
                fi
                ;;
        esac
    done
}

if [ "$1" = "--restore" ]; then
    restore
else
    menu_loop
fi
