#!/bin/sh

wids=$(xdotool search --class Zathura)
[ -z "$wids" ] && exit 0
currwid=$(xdotool getactivewindow)

for wid in $wids; do
	if echo "$wid" | xargs xdotool getwindowname | grep -qv  'org.pwmt.zathura'; then
        xdotool windowactivate "$wid"
		xdotool key --delay 24 --window "$wid" ctrl+c colon s o u r c e enter
	fi
done
xdotool windowactivate "$currwid"
