#!/bin/sh

# human-readable name;urlname;icon
refname="usd"
refsym="$"
coins="Bitcoin;btc;
Etherium;eth;
Cardano;ada;
Polkadot;dot;
Binance Coin;bnb;
Monero;xmr;
Chain Link;link;
Basic Attention Token;bat;
LBRY Credits;lbc;"

# Directory where currency info is stored.
dir="${XDG_DATA_HOME:-$HOME/.local/share}/crypto-prices"
interval="@7d"

refresh='累 '

update() {
    rm -rf "${dir:?}/*"
	echo "$coins" | while IFS=';' read -r human coin icon; do
		val="$(curl -s "$refname.rate.sx/1$coin")" &&
            echo "$icon;$val$refsym;$human" > "$dir/$coin-price" &&
            curl -s "$refname.rate.sx/$coin$interval" > "$dir/$coin-chart"
	done; [ -d "$dir" ] && touch "$dir"
}

echo "$refresh$(sb-crypto)" > /tmp/cryptoupdate
pkill -RTMIN+13 "${STATUSBAR:-dwmblocks}"
notify-send "updating!"

[ ! -d "$dir" ] && mkdir -p "$dir"
ping -q -c 1 example.org >/dev/null 2>&1 && update || notify-send "No Network!"
rm -f /tmp/cryptoupdate

pkill -RTMIN+13 "${STATUSBAR:-dwmblocks}"
