#!/bin/sh

# Set as a cron job to check for new RSS entries for newsboat.
# If newsboat is open, sends it an "R" key to refresh.

refresh='累 '

ping -q -c 1 example.org > /dev/null || exit

pgrep -f newsboat$ && /usr/bin/xdotool key --window "$(/usr/bin/xdotool search --name newsboat)" R && exit # TODO name is actually st

echo "$refresh$(cat /tmp/newsupdate)" > /tmp/newsupdate
pkill -RTMIN+6 "${STATUSBAR:-dwmblocks}"
sleep 1
rm -f /tmp/newsupdate

/usr/bin/newsboat -x reload

pkill -RTMIN+6 "${STATUSBAR:-dwmblocks}"
