#!/bin/sh

# Set as a cron job to check for new RSS entries for newsboat.
# If newsboat is open, sends it an "R" key to refresh.

refresh='累 '

ping -q -c 1 example.org > /dev/null || exit

pgrep -f newsboat$ && /usr/bin/xdotool key --window "$(/usr/bin/xdotool search --name newsboat)" R && exit # TODO name is actually st

echo "$refresh$(sb-news)" > /tmp/newsupdate

pkill -RTMIN+6 "${STATUSBAR:-dwmblocks}"

/usr/bin/newsboat -x reload
rm -f /tmp/newsupdate

pkill -RTMIN+6 "${STATUSBAR:-dwmblocks}"
